# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -DLMP_USER_MESO 
PKG_PATH =  
PKG_LIB =   

PKG_SYSINC =  $(user-meso_SYSINC) 
PKG_SYSLIB =  $(user-meso_SYSLIB) 
PKG_SYSPATH = $(user-meso_SYSPATH) 
